apiVersion: v1
kind: Service
metadata:
    name: go-hello-world
spec:
    type: NodePort # issues a high number port that will be available in the gateway node, get the port for the service so youcan route traffic from 80 -> to that port.
    ports:
    - port: 8080
      targetPort: 8080
    selector:
      app: go-hello-world
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: go-hello-world-deployment
spec:
    replicas: 2
    template:
        metadata:
            labels:
                app: go-hello-world
        spec:
            containers:
            - name: go-hello-world
              image: "docker.io/rpaul80/go-hello-world"
              ports:
              - containerPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: go-hello-world
  namespace: default
spec:
  backend:
    serviceName: go-hello-world
    servicePort: 8080
